---
- name: Create a custom Docker network
  community.docker.docker_network:
    name: custom_net
    driver: bridge

- name: Pull Nginx Docker image
  docker_image:
    name: nginx
    tag: latest
    source: pull
  tags:
    - pull-nginx-image

- name: Copier la configuration Nginx
  ansible.builtin.copy:
    src: nginx.conf
    dest: /tmp/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: Run Nginx container
  docker_container:
    name: nginx
    image: nginx:latest
    state: started
    ports:
      - "80:80"
    networks:
      - name: custom_net
    volumes:
      - /tmp/nginx.conf:/etc/nginx/nginx.conf:ro
  tags:
    - run-nginx-container

- name: Ensure Nginx container is running
  docker_container:
    name: nginx
    state: started
  tags:
    - ensure-nginx-running
